### ISSUE TITLE
Listen for "container started" events instead

### ISSUE THREAD

**Issue by boosty** [xing/kubernetes-oom-event-generator#3]
We are currently listening to all pod change events:
https://github.com/xing/kubernetes-oom-event-generator/blob/d858dd80dcd2cd09bae64827e2ed8dbbe27e7206/src/controller/controller.go#L56-L60

This seems a bit wasteful, as we also have to keep a custom container restart counter. 

I suggest that we have a closer look at listening for "container started" events instead.

**Comment by 0robustus1** [comment]
integrated with #4.
